FROM python:3.4-onbuild

EXPOSE 2666
VOLUME /mnt/cv
WORKDIR /mnt/cv/wlskout

# docker create -it -v "$(dirname $PWD)":/mnt/cv -w /mnt/cv/wlskout --expose=2666 -P --name=sever 23d1a python responder.py
# docker create -it -v "$(dirname $PWD)":/mnt/cv -w /mnt/cv/wlskout --expose=2666 -P --name=responder --link=server 23d1a python responder.py

